"""Generate the Flask dashboard fallback from the canonical page source."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "pages" / "dashboard" / "index.html"
TARGET = ROOT / "webui" / "index_fallback.py"


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    TARGET.write_text(
        "\"\"\"Generated by scripts/generate_dashboard_fallback.py; do not edit.\"\"\"\n\n"
        "INDEX_HTML = " + json.dumps(text, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
